name = "playwright-mcp-example"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[browser]
binding = "BROWSER"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PlaywrightMCP"]

[[migrations]]
tag = "v2"
deleted_classes = []

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "PlaywrightMCP"

[[kv_namespaces]]
binding = "SESSION_STORAGE"
id = "adc985d8e536407fb8135b7919ec664e"
